force-app/main/default/objects/AppointmentSlot__c/AppointmentSlot__c.object-meta.xml
<CustomObject>
    <description>The available time slots for appointments with any healthcare professional. It allows patients to select from available times for appointments with doctors, nurses, therapists, or other healthcare providers.</description>
    <label>Appointment Slot</label>
    <nameField>
        <displayFormat>SL-{0000}</displayFormat>
        <label>Appointment Slot Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Appointment Slots</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/AppointmentSlot__c/fields/AppointmentDate__c.field-meta.xml
<CustomField>
    <fullName>AppointmentDate__c</fullName>
    <description>The day and time when the Appointment would take place.</description>
    <label>Appointment Date</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/AppointmentSlot__c/fields/Specialty__c.field-meta.xml
<CustomField>
    <fullName>Specialty__c</fullName>
    <description>A Medical Specialty is a branch of medicine that focuses on a specific area or system of the body, or a particular patient population. Practitioners of a specialty undergo specialized training, education, and certification to provide advanced care and expertise in their area of specialization.</description>
    <inlineHelpText>Select the doctor&apos;s medical specialty from the list. This indicates their advanced training and expertise in a specific area of medicine, ensuring the patient receives appropriate care.</inlineHelpText>
    <label>Specialty</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>MedicalSpecialties</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/MedicalSpecialties.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Anesthesiology</fullName>
    </customValue>
    <customValue>
        <fullName>Cardiology</fullName>
    </customValue>
    <customValue>
        <fullName>Dermatology</fullName>
    </customValue>
    <customValue>
        <fullName>Endocrinology</fullName>
    </customValue>
    <customValue>
        <fullName>Family medicine</fullName>
    </customValue>
    <customValue>
        <fullName>Gastroenterology</fullName>
    </customValue>
    <customValue>
        <fullName>Hematology</fullName>
    </customValue>
    <customValue>
        <fullName>Internal medicine</fullName>
    </customValue>
    <customValue>
        <fullName>Laboratory Medicine</fullName>
    </customValue>
    <customValue>
        <fullName>Neurology</fullName>
    </customValue>
    <customValue>
        <fullName>Obstetrics and gynecology</fullName>
    </customValue>
    <customValue>
        <fullName>Oncology</fullName>
    </customValue>
    <customValue>
        <fullName>Ophthalmology</fullName>
    </customValue>
    <customValue>
        <fullName>Orthopedics</fullName>
    </customValue>
    <customValue>
        <fullName>Otolaryngology (ENT)</fullName>
    </customValue>
    <customValue>
        <fullName>Pediatrics</fullName>
    </customValue>
    <customValue>
        <fullName>Psychiatry</fullName>
    </customValue>
    <customValue>
        <fullName>Pulmonology</fullName>
    </customValue>
    <customValue>
        <fullName>Radiology</fullName>
    </customValue>
    <customValue>
        <fullName>Rheumatology</fullName>
    </customValue>
    <customValue>
        <fullName>Surgery</fullName>
    </customValue>
    <description>This is a list of medical specialties</description>
    <masterLabel>Medical Specialties</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/AppointmentSlotsGraph.cls
public without sharing class AppointmentSlotsGraph
{
	@TestVisible
	private Map<Id, Node> nodesById;

	@TestVisible
	private Map<Id, List<Edge>> edgesByNodeId;
	
	// minimumGapTime in milliseconds
	public AppointmentSlotsGraph(List<AppointmentSlot__c> slots, Long minimumGapTime, Boolean isSorted)
	{
		nodesById = new Map<Id, Node>();
		edgesByNodeId = new Map<Id, List<Edge>>();
		// Fill the Nodes map with the provided slots
		for (AppointmentSlot__c slot : slots)
		{
			nodesById.put(slot.Id, new Node(slot.Id, slot.AppointmentDate__c, slot.Specialty__c));
		}

		// Create the edges based on the slot's times and categories
		createEdges(minimumGapTime, isSorted);
	}

	private void createEdges(Long minimumGapTime, Boolean isSorted)
	{
		/*
		* An edge is created only if:
		* - The second Node is of a different Specialty
		* - The second Node is at more than the "minimumGapTime" further ahead from the first.
		*/

		// if the List is sorted we can use a slightly more efficient loop.
		if (isSorted)
		{
			List<Node> slots = nodesById.values();
			Node firstNode;
			Node secondNode;
			Long timeDifference;
			for (Integer i = 0; i < slots.Size() - 1; i++)
			{
				firstNode = slots[i];

				for (Integer j = i + 1; j < slots.Size(); j++)
				{
					secondNode = slots[j];
					timeDifference = secondNode.slotTime.getTime() - firstNode.slotTime.getTime();
					
					if (firstNode.specialty != secondNode.specialty &&
						timeDifference > minimumGapTime)
					{
						// If the value is not yet in the Edges list, initialize it first
						if (!edgesByNodeId.containsKey(firstNode.Id))
						{
							edgesByNodeId.put(firstNode.Id, new List<Edge>());
						}
						edgesByNodeId.get(firstNode.Id).add(new Edge(secondNode.Id, timeDifference));
					}
				}
			}

		}
		else
		{
			
		}
	}

	@TestVisible
	private class Node 
	{
		public Id id;
		public Datetime slotTime;
		public string specialty;
		
		public Node (Id idP, Datetime timeP, String specialtyP)
		{
			id = idP;
			slotTime = timeP;
			specialty = specialtyP;
		}
	}

	@TestVisible
	private class Edge
	{
		public Id nodeId; // Id of the Node that this edge is pointing to.
		public Long weight;

		public Edge(Id nodeIdP, Long weightP)
		{
			nodeId = nodeIdP;
			weight = weightP;
		}
	}
}